#ifndef LIBBLOCKDIA_GLOBALS_H
#define LIBBLOCKDIA_GLOBALS_H

#include <QtCore/qglobal.h>
#if defined(LIBBLOCKDIA_LIBRARY)
#  define LIBBLOCKDIASHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBBLOCKDIASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBBLOCKDIA_GLOBALS_H
